name: Build and Test

on:
  pull_request:
    branches: 
      - 'develop'
      - main
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - 'develop'
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    # .NETのセットアップ
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x' # .NETバージョンに応じて調整

    # GitHub Packages 用の NuGet 認証の設定
    - name: Configure GitHub Packages
      run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"


    # パッケージ復元
    - name: Restore dependencies
      run: dotnet restore

    # ビルド
    - name: Build
      run: dotnet build --no-restore -c Release

    # テスト
    - name: Test
      run: dotnet test --no-build -c Release